Repository crossplatformkorea/flutter_boilerplate, pull requests merged in 2022-10, with the labels that each got.

#9 feat: add description on freezed package
  README.md
  lib/controllers/user_controller.dart
  lib/models/user.dart
  lib/models/user.freezed.dart
  lib/models/user.g.dart
  test/models/user_test.dart
  test/units/fetch_user_test.dart
Labels: 🎯 feature

#13 refactor: getx제거후, provider로 대체
  lib/controllers/count_controller.dart
  lib/controllers/user_controller.dart
  lib/main.dart
  lib/screens/edit_profile.dart
  lib/screens/home.dart
  lib/screens/result.dart
  lib/utils/helpers.dart
  lib/utils/themes.dart
  lib/widgets/back_app_bar.dart
  lib/widgets/edit_text.dart
  lib/widgets/model_theme.dart
  lib/widgets/my_theme_preferences.dart
  pubspec.lock
  pubspec.yaml
  test/test_utils.dart
  test/widgets/home_test.dart
  test/widgets/responsive_test.dart
  test/widgets/result_test.dart
Labels: ⌛️ revert, ፦ refactor

#14 chore: 라이브러리 최신화, readme수정
  README.md
  pubspec.lock
  pubspec.yaml
Labels: 📖 documentation, 👷‍♀️ build
